/*
 * @Author: zuo
 * @Date: 2026-01-12 09:30:43
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { ThemeProvider, useTheme } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from '@/components/Navbar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        
      >
        <ThemeProvider
          attribute="class" // 关键：通过给 html 标签加 class="dark" 来切换主题
          defaultTheme="system" // 默认跟随系统
          enableSystem
          disableTransitionOnChange // 避免切换时的闪烁
        >
          <Navbar /> 
            {children}
          <Toaster />
        </ThemeProvider>
        
      </body>
    </html>
  );
}
